=== DraconPern/medcommons-/router/demo/bin/etc/schema/editsession/EditSession10.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
    xmlns:xs="http://www.w3.org/2001/XMLSchema" 
    xmlns:es="http://www.medcommons.net/editsession01" 
    targetNamespace="http://www.medcommons.net/editsession01"
    elementFormDefault="qualified" attributeFormDefault="unqualified"
    >
<xs:element name="EditSession" type="es:EditSessionType">
    <xs:annotation>
        <xs:documentation>
            Defines an edit session with a server. This message contains REST URIs for
            GETting and PUTting content back to the server and some status information; 
            it also contains some other values which can be used for application display
            (patient name, patient pictures, application title), application features 
            (select alternative profile). Lastly - some of the values (SessionToken and
            AuthorizationToken) can be used to create other secure URIs based on the 
            the contents of the CCR (such as downloading a reference).
        </xs:documentation>
    </xs:annotation>
    
</xs:element>
<xs:complexType name="EditSessionType">
    <xs:sequence>
        
        <xs:element name="SessionToken" type="xs:string"  minOccurs="1"  maxOccurs="1">
            <xs:annotation><xs:documentation>The session handle which identifies this session</xs:documentation></xs:annotation>
        </xs:element>
        <xs:element name="ContentType" type="xs:string"  minOccurs="1" maxOccurs="1">
            <xs:annotation><xs:documentation>The ContentType of the SessionURI.</xs:documentation></xs:annotation>
        </xs:element>
        <xs:element name="AuthorizationToken" type="xs:string"  minOccurs="1" maxOccurs="1">
            <xs:annotation><xs:documentation>
                A security token which is valid with this session.
            </xs:documentation></xs:annotation>
        </xs:element>
        <xs:element name="SessionURI" type="xs:string"  minOccurs="1" maxOccurs="1">
            <xs:annotation><xs:documentation>
                This is the URI which defines the resource being edited. Initially it is 
                retrieved with a HTTP GET; changes are pushed back via a PUT.
            </xs:documentation></xs:annotation>
        </xs:element>
        <xs:element name="Alias" type="xs:string" minOccurs="0" maxOccurs="1">
            <xs:annotation><xs:documentation>
                Human-readable alias for the session. Typically something like "Current CCR" or "Emergency CCR".
            </xs:documentation></xs:annotation>
        </xs:element>
        <xs:element name="PersonName" type="xs:string" minOccurs="0" maxOccurs="1">
            <xs:annotation><xs:documentation>
                The name of the person to whom the resource refers to (typically the patient).
            </xs:documentation></xs:annotation>
        </xs:element>
        <xs:element name="PersonImage" type="xs:string" minOccurs="0" maxOccurs="1">
            <xs:annotation><xs:documentation>
                A base64 encoded PNG image of the person to whom the resource refers to (typically the patient).
            </xs:documentation></xs:annotation>
        </xs:element>
        <xs:element name="ApplicationTitle" type="xs:string" minOccurs="0" maxOccurs="1">
            <xs:annotation><xs:documentation>
               The name that the launched application displays (typically in a title bar).
            </xs:documentation></xs:annotation>
        </xs:element>
        <xs:element name="Status" type="xs:string" minOccurs="0" maxOccurs="1">
            <xs:annotation><xs:documentation>
                The status of the transaction. Status codes here match HTTP semantics - codes in the 200-299 range
                mean success; 300 means redirection; 500 means server error, &amp;etc.
            </xs:documentation></xs:annotation>
        </xs:element>
        <xs:element name="Reason" type="xs:string" minOccurs="0" maxOccurs="1">
            <xs:annotation><xs:documentation>
                A text field linked to status. For a Status of 200 - the reason is typically 'OK'. For an error 
                it contains some details of the error which can be displayed to the user.
            </xs:documentation></xs:annotation>
        </xs:element>
        <xs:element name="RedirectURI" type="xs:string" minOccurs="0" maxOccurs="1">
            <xs:annotation><xs:documentation>
                If the status code is in the 300-399 range then the calling application should redirect 
                the user to this URI. Typically this is due to a authentication or transaction failure and
                the user must use the browser to re-establish credentials or create a new transaction.
            </xs:documentation></xs:annotation>
        </xs:element>
        <xs:element name="Profiles" minOccurs="0" maxOccurs="1">
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="Profiles" type="es:ProfileType" maxOccurs="unbounded"/>
                </xs:sequence>
            </xs:complexType>
        </xs:element>
    </xs:sequence>
</xs:complexType>
    
    <xs:complexType name="ProfileType">
        <xs:annotation>
            <xs:documentation>
                A profile is a Alias/RequestSessionURI pair which are used for creating alternative sessions. 
                A typical application will display the alias values in a menu and when the user
                selects them an alternative session is requested via the RequestSessionURI.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="Alias" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="RequestSessionURI" type="xs:string" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== DraconPern/medcommons-/router/demo/bin/etc/schema/editsession/EditSessionExample.xml
<?xml version="1.0" encoding="UTF-8"?>
<EditSession xmlns="http://www.medcommons.net/editsession01"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.medcommons.net/editsession01 file:/Users/mesozoic/Documents/MedCommons/svn.medcommons.net/router/demo/etc/schema/editsession/EditSession10.xsd">
    <SessionToken>381610e8803f81bb4f8ae11fb38c98ceb2e98d2b</SessionToken>
    <ContentType>ContentType0</ContentType>
    <AuthorizationToken>AuthorizationToken0</AuthorizationToken>
    <SessionURI>http://stego.myhealthespace.com:9080/router/DocumentEditSession?token=381610e8803f81bb4f8ae11fb38c98ceb2e98d2b</SessionURI>
    <Alias>Current CCR</Alias>
    <PersonName>Stella Paterson</PersonName>
    <PersonImage>(base64 encoded image)</PersonImage>
    <ApplicationTitle>The Amazing HeathBook (tm)</ApplicationTitle>
    <Status>200</Status>
    <Reason>OK</Reason>
    <Profiles>
        <Profiles>
            <Alias>Current CCR</Alias>
            <RequestSessionURI>http://stego.myhealthespace.com/router/getPHREditSession?storageId=1088448116240388&amp;reference=CurrentCCR</RequestSessionURI>
        </Profiles>
        <Profiles>
            <Alias>Emergency CCR</Alias>
            <RequestSessionURI>http://stego.myhealthespace.com/router/getPHREditSession?storageId=1088448116240388&amp;reference=EmergencyCCR</RequestSessionURI>
        </Profiles>
    </Profiles>
</EditSession>
